### ISSUE TITLE
consider having code roles write a code-setup.yml

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#108]
Currently, the setup of AiiDA codes is handled by the AiiDA role, using variables from the `default.yml` of the respective code roles.
This works, but it means the information about code versions etc. is only available from ansible.

It might be advantageous to have e.g. marvel-nccr.cp2k write a cp2k.yml file in a specific folder (perhaps in `~/.aiida`) that can be used both by the aiida role and by remote users (in the case of a workhorse server) to set up the AiiDA connection.

**Comment by ltalirz** [comment]
Note: the yml file should *not* contain the `computer` field - this can easily be added when using it via `verdi code setup --config file.yml`

e.g.
```yaml
label: "raspa-2.0.37"
description: "RASPA2 cloned from https://github.com/iRASPA/RASPA2.git"
input_plugin: "raspa"
on_computer: true
remote_abs_path: "/usr/local/bin/simulate"
prepend_text: |
  export RASPA_DIR=/work/lsmo/aiida-lsmo-codes/data/raspa
  export DYLD_LIBRARY_PATH=/work/lsmo/aiida-lsmo-codes/lib/raspa_4467e14_deneb
  export LD_LIBRARY_PATH=/work/lsmo/aiida-lsmo-codes/lib/raspa_4467e14_deneb
append_text: " "
```
