### ISSUE TITLE
ubuntu desktop glitches

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/quantum-mobile#93]
- [ ] after running `vagrant up`, the user is not logged in. Logging in with the right credentials works but then logs you out again right away. Only workaround: restart the VM
 - [ ] the desktop icons for faq and apps do not yet show the logo. workaround: open them once

**Comment by ltalirz** [comment]
It turns out issue 1 was caused by [this](https://github.com/marvel-nccr/ansible-role-ubuntu-desktop/blob/a5448c9a1d08051e50492c6bb0632c52a2d7509d/tasks/disable_autolock.yml#L23-L33) task of the `ubuntu-desktop` role:
```yaml
- name: disable automatic suspend
  become: true
  become_user: "{{ ubuntu_desktop_vm_user }}"
  dconf:
    key: "{{ item }}"
    value: "'nothing'"
    state: absent
  with_items:
    - /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
    - /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
  notify: restart gdm3
```
Note: Even after removing the dconf value with `state: absent`, restarting gdm3 was not enough. The system needed to be restarted in order for the fix to work.
